tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "ccls"
brew "cmake"
brew "composer"
brew "coreutils"
brew "docker"
brew "docker-machine"
brew "exa"
brew "fzf"
brew "gcc"
brew "ghostscript"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "gpg"
brew "gpg2"
brew "gradle"
brew "htop"
brew "imagemagick"
brew "jpeg"
brew "jpeg-turbo"
brew "kotlin"
brew "libffi"
brew "librsvg"
brew "libtiff"
brew "libxml2"
brew "libxmlsec1"
brew "libxslt"
brew "mysql"
brew "node", link: false
brew "nvm"
brew "octave"
brew "openssl"
brew "php", link: false
brew "pinentry-mac"
brew "postgresql"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python"
brew "qt"
brew "r"
brew "ranger"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "rust"
brew "sqlite"
brew "sshfs"
brew "telnet"
brew "the_silver_searcher"
brew "tree"
brew "vim"
brew "webp"
brew "wget"
brew "zlib"

cask "alfred3"
cask "discord"
cask "dropbox"
cask "firefox"
cask "gimp"
cask "google-chrome"
cask "iterm2"
cask "java"
cask "mactex"
cask "microsoft-office"
cask "slack"
cask "snagit"
cask "spectacle"
cask "spotify"
cask "thunderbird"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"

brew "mas"
mas "DaftCloud", id: 1320450034
mas "GCal for Google Calendar", id: 1107163858
mas "Harvest", id: 506189836
mas "LastPass", id: 926036361
mas "Microsoft Remote Desktop", id: 1295203466
mas "MobilePASS", id: 972648459
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Telephone", id: 406825478
mas "Xcode", id: 497799835
